### ISSUE TITLE
DNS rebinding

### ISSUE THREAD

**Issue by ghost** [angristan/local-dns-resolver#23]

**Comment by angristan** [comment]
I don't understand :(

**Comment by cezar97** [comment]
I mean we should include that directive for protection against DNS rebinding. Just don't know where to put it in the code without "bloating" it due to the many IP's.

**Comment by angristan** [comment]
I meant I don't understand what DNS rebinding is :/

**Comment by cezar97** [comment]
To make it simple, I could explain it like the following:
You go to a malicious site that contains a frame. The domain loaded in the frame has as the ip a private one, so let's say 192.168.0.1, that's the router page. So the site, having access to the frame, could run scripts or interact with the router page in this case. That's why we can also say that this technique use the browser as a proxy to access other PCs on the private network.

**Comment by angristan** [comment]
Oh ok. Indeed enabling it for RFC1918 IPs would be a good idea, but since when is this feature available in unbound?

**Comment by cezar97** [comment]
Right, I didn't take into account OS support. Anyway, looking at the changelog, they introduced this with v1.1.0 ( November 2008 ), so we're covered :smiley:. In this changelog they also said to set this as default, but after 10 years they didn't :neutral_face:.

**Comment by ghost** [comment]
hello. thanks for the script i just trayed on cenos 7 vm and its work but i cannot query dns request from another vm whit dns ip of vm dns server, my gol is setup two centos 7 dns servers for my home lan network primary and secondary that primery will backup secondary and secondary will backup primary, can you make script for this in your spare time? i searched on google nothinkg can find that works.

**Comment by cezar97** [comment]
Hello, I'll paste you an awesome guide that helped me start with Unbound. It covers everything you have to know like caching, primary and secondary for backup... 
Here's the site: https://calomel.org/unbound_dns.html.

**Comment by angristan** [comment]
Fixed in #26
